### PR TITLE
Better editor and merlin integration by improving ppx locations

### LINKED ISSUE #429: merlin and RLS broken for JSX3 components
https://youtu.be/Hf6hEqHqpG4 shows the issues for ReasonReact JSX3 + GraphQL, but this is also the case even for simple components:

```reason
open React;
open! ReasonReact;

type state = {
  count: int,
  show: bool,
};

type action =
  | Click(int)
  | Toggle;

let initialState = {count: 0, show: true};

[@react.component]
let make = (~greeting) => {
  let (state, dispatch) =
    useReducer(
      (state, action) =>
        switch (action) {
        | _ => state
        | Click(points) => {...state, count: state.count + points}
        | Toggle => {...state, show: !state.show}
        },
      initialState,
    );

  let message =
    "You've clicked this " ++ string_of_int(state.count) ++ " times(s)";

  <div>
    <button onClick={_ => dispatch(Click(10))}> {string(message)} </button>
    <button onClick={_ => dispatch(Toggle)}>
      {string("Toggle greeting")}
    </button>
    {state.show ? string(greeting) : null}
  </div>;
};
```

The issue for this smaller component show up in weird places. Asking for the type under lots of locations works, but asking for the type of `points` under  `| Click(points) =>` expands the selection to the whole function (everything after `let make = `. Same thing for checking `dispatch` in `let (state, dispatch)`, though `state` works fine.

Similarly for `{state.show ? string(greeting) : null}`, these tokens work: `state`, `string`, `null`
and these expand the selection to the full component `show` (in `state.show`), `greeting`

Screenshot 2019-05-17 18 51 01
Screenshot 2019-05-17 18 50 43

### PR DESCRIPTION
**Pull request by jchavarri**
Fixes #429.

The fix is kind of similar to the one used [in jsoo-react](https://github.com/ml-in-barcelona/jsoo-react/pull/134), but adapted to the current state of this ppx.

It is based on these ideas:

- Avoid using `Location.none`, especially on intermediate ast nodes. Using `Location.none` completely disables merlin ability to find back an ast node for a given location
- Try to build locations in a consistent way with the ast tree. for what "consistent" means, check [this explanation](https://github.com/ocaml/ocaml/pull/8987) by trefis
- Hide subparts of the ast with `merlin.hide` (when we want to hide whole subtree) or `loc_ghost` (for just one node)
- Use `-dparsetree` in tests to both check which locations are set to none or inconsistent, and see how changes in ppx affect the result

~The PR adds some tests using `-dparsetree` to see how changes in the ppx affect locations in real code. Unfortunately I am not able to set up a test that involves merlin as well, so what I do for testing, besides looking at the output in the newly added `ppx/test/output_locations.expected`, is:~
~- Change `reactjs_jsx_ppx.ml`~
~- `make build`~
~- Hover over elements in `test/React__test.re`~

~This is a quite fast workflow.~ Edit: tests using merlin directly are being added in #749.

Here are some gifs to show comparison between `main` and this branch.

### Case 1: Component in `React__test.re`

| `main`  | This branch |
| ------------- | ------------- |
| case-1-ppx-locs-before | case-1-ppx-locs-after |

### Case 2: The component reported in original issue #429

| `main`  | This branch |
| ------------- | ------------- |
| case-2-ppx-locs-before | case-2-ppx-locs-after |

### CODE REVIEW

**Comment by jchavarri** [comment]
There was a comment by Ricky about some tradeoff between optimizing for good errors or for merlin integration [in the original issue](https://github.com/reasonml/reason-react/issues/429#issuecomment-567561769).

Unfortunately no examples of this tradeoff were provided, I have tested with unused props, go to definition in props, type errors in props, etc. and all the tests I did were successful, in all cases both Merlin and the compiler can figure things out fine.

File: ppx/src/reactjs_jsx_ppx.ml [hunk 1]
```diff
@@ -122,6 +122,15 @@ let unerasableIgnore loc =
     attr_loc = loc;
   }
 
+(* [merlinHide] tells merlin to not look at a node, or at any of its
+   descendants. *)
+let merlinHide =
+  {
```
Comment (anmonteiro) [inline ppx/src/reactjs_jsx_ppx.ml:128]: this is only ever used as a list with a single element. we could allocate that list just once here.

Comment (jchavarri) [reply ppx/src/reactjs_jsx_ppx.ml]: good point, fixed in https://github.com/reasonml/reason-react/pull/748/commits/ea0292763721fc82e95d16562bf4325af8c71bbb.
